language: node_js

node_js:
  - "node"

before_install:
  - rvm install 2.2
  - gem install awesome_bot
  - gem install danger

before_script:
  - git diff master.. -U0 README.md | grep -Po "(?<=^\+).*" >> temp.md

script:
  - node test.js temp.md
  - awesome_bot temp.md --allow-redirect
  - danger --verbose
