language: node_js

node_js:
  - "node"

cache:
  npm: false

before_install:
  - rvm install 2.6.2
  - gem install awesome_bot
  - sudo apt update && sudo apt install python3-pip python3-setuptools
  - cd tests && npm install chalk && cd ..

script:
  - 'echo "DEBUG: $TRAVIS_BRANCH - $TRAVIS_EVENT_TYPE - $TRAVIS_PULL_REQUEST"'
  - 'if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "cron" ]]; then make check_all; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make check_pr; fi'

notifications:
  email: false
